services:
  dcc_api:
    build: .
    container_name: dcc_api
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ${HF_CACHE_PATH:-./hf_cache}:/root/.cache/huggingface
      - .:/dcc
      - ~/.cache/pip:/root/.cache/pip
    environment:
      - HF_HOME=/root/.cache/huggingface
      - MYSQL_HOST=${MYSQL_HOST:-dcc_db}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_USER=${MYSQL_USER:-dutchman}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-dutch_comments}
      - DEV_MODE=${DEV_MODE:-0}
    depends_on:
      - dcc_ollama
      - dcc_db
      - dcc_redis
    restart: unless-stopped
    working_dir: /dcc
    command: bash shell/api_entrypoint.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  dcc_ollama:
    image: ollama/ollama:latest
    container_name: dcc_ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  dcc_db:
    image: mysql:8.0
    container_name: dcc_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-example}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-dutch_comments}
      MYSQL_USER: ${MYSQL_USER:-dutchman}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  dcc_redis:
    image: redis:7
    container_name: dcc_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
