"""initial

Revision ID: 47c08201de53
Revises: 
Create Date: 2025-07-12 03:11:37.799652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47c08201de53'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('translanted_comment', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('translated_subject', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('translated_context', sa.Text(), nullable=True),
    sa.Column('spam', sa.Float(), nullable=True),
    sa.Column('ham', sa.Float(), nullable=True),
    sa.Column('toxic', sa.Float(), nullable=True),
    sa.Column('insult', sa.Float(), nullable=True),
    sa.Column('obscene', sa.Float(), nullable=True),
    sa.Column('identity_hate', sa.Float(), nullable=True),
    sa.Column('severe_toxic', sa.Float(), nullable=True),
    sa.Column('threat', sa.Float(), nullable=True),
    sa.Column('llm_escalation_results', sa.Text(), nullable=True),
    sa.Column('llm_remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
