"""Initial migration

Revision ID: 79d66102f398
Revises: 
Create Date: 2025-07-12 03:45:45.169024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d66102f398'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ext_id', sa.String(length=100), nullable=True, comment="The user application's subject (article or whatever's the subject of a comment) id"),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('translated', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ext_id'),
    sa.UniqueConstraint('ext_id', name='_extid_uc')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('translanted_text', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True, comment="Can be used for things like the article's first paragraph, or another comment that this comment is replying to. Basically our attempt to 'contextualize' this comment"),
    sa.Column('translated_context', sa.Text(), nullable=True),
    sa.Column('spam', sa.Float(), nullable=True),
    sa.Column('ham', sa.Float(), nullable=True),
    sa.Column('toxic', sa.Float(), nullable=True),
    sa.Column('insult', sa.Float(), nullable=True),
    sa.Column('obscene', sa.Float(), nullable=True),
    sa.Column('identity_hate', sa.Float(), nullable=True),
    sa.Column('severe_toxic', sa.Float(), nullable=True),
    sa.Column('threat', sa.Float(), nullable=True),
    sa.Column('llm_escalation_results', sa.Text(), nullable=True),
    sa.Column('llm_remarks', sa.Text(), nullable=True),
    sa.Column('llm_last_processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('subjects')
    # ### end Alembic commands ###
