"""Comment moderation

Revision ID: 90ea1f7c62c3
Revises: c41b9dc38284
Create Date: 2025-07-13 12:08:26.017608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '90ea1f7c62c3'
down_revision: Union[str, Sequence[str], None] = 'c41b9dc38284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_moderation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('llm_comment_analyses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_comment_analyses',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('model_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('results', mysql.TEXT(), nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.Column('processed_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('llm_comment_analyses_ibfk_1')),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('llm_comment_analyses_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('comment_moderation_results')
    # ### end Alembic commands ###
