"""Add missing classifier_flagged_as column

Revision ID: eb60807f0261
Revises: 90ea1f7c62c3
Create Date: 2025-07-13 13:19:47.118440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb60807f0261'
down_revision: Union[str, Sequence[str], None] = '90ea1f7c62c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_moderation_results', sa.Column('classifier_flagged_as', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment_moderation_results', 'classifier_flagged_as')
    # ### end Alembic commands ###
